# Generated by Django 3.0.2 on 2020-02-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fail',
            fields=[
                ('Fail_id', models.AutoField(primary_key=True, serialize=False)),
                ('Fail_college', models.CharField(max_length=255)),
                ('Fail_partment', models.CharField(max_length=255)),
                ('Fail_title', models.CharField(max_length=255)),
                ('Fail_time', models.CharField(max_length=255)),
                ('Fail_detail_time', models.CharField(max_length=255)),
                ('Fail_site', models.CharField(max_length=255)),
                ('Fail_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('Seminar_id', models.AutoField(primary_key=True, serialize=False)),
                ('Seminar_title', models.CharField(max_length=255)),
                ('Seminar_time', models.CharField(max_length=255)),
                ('Seminar_site', models.CharField(max_length=100)),
                ('Seminar_college', models.CharField(max_length=255)),
                ('Seminar_partment', models.CharField(max_length=255)),
                ('Seminar_url', models.CharField(max_length=255)),
            ],
        ),
    ]
